### ISSUE TITLE
Socket closed by remote peer 

### ISSUE THREAD

**Issue by ysnnzlcn** [leonliu/NPDesktop#8]
Hi,
I am trying to connect vnc server but server kicks me out with this error. I can successfully connect Mac machines but can't connect other vnc servers. I am the only one trying to connect so it can't be because of multiple users. 

When i comment out pixel setting;
```
conn.sendSetPixelFormat(format)
self.rfbView.frameBuffer?.pixelFormat = format
```
 the error goes away, server is getting touch events but this time there are no visuals.
Any ideas?

**Comment by leonliu** [comment]
hi,

I suspect the pixel format is not compatible with server side so it silently does  not respond with screen data. You may check the log to see what happens.

**Comment by YasinMaySiber** [comment]
Thanks for replying I think I found the problem. When I connect the server with another app to see its settings, this came up;

![screen shot 2018-04-02 at 22 20 08](https://user-images.githubusercontent.com/34395644/38304279-8239f6f6-3811-11e8-8511-6d5e47275642.png)

So I guess the server is waiting for TRLE encoding but we can connect to it with Hextile(interesting), and this library doesn't support both encoding types.

**Comment by ysnnzlcn** [comment]
Thanks for replying I think I found the problem. When I connect the server with another app to see its settings, this came up;

![asdas](https://user-images.githubusercontent.com/30194773/38304429-1d96cbd8-3812-11e8-8033-8ffd0c460601.png)


So I guess the server is waiting for TRLE encoding but we can connect to it with Hextile(interesting), and this library doesn't support both encoding types.

**Comment by leonliu** [comment]
This is weird if the server supports TRLE only since TRLE is not well documented. Check this SO link out https://stackoverflow.com/questions/39175606/rfb-vnc-client-in-c-trle-encoding, I think it may help.

**Comment by ysnnzlcn** [comment]
I checked the link and one of answers says 

> It would be very weird if the server you are connecting to only supports TRLE and nothing else, but in that case you can still request "just RAW" data.

Are we able to do that manually with this library? I tried to change encodings settings but couldn't find anything except `conn.sendSetEncodings()`. Which seems like; it automatically sends all encoding types its supported.

Any idea?

**Comment by leonliu** [comment]
if  my memory is correct, the protocol works as the client sends all the encoding types it supports and the server responds with which is accept. You may turn on the debug logging to see what happened.
